### ISSUE TITLE
Detekcija nošenja zaštitnih maski na videu u realnom vremenu korišćenjem kompjuterske vizije

### ISSUE THREAD

**Issue by Vukeezy** [ftn-ai-lab/sc-2020-siit#1]
**Tim**
Vukašin Ocokoljić, sw60/2017
Romana Erdelji, sw58/2017
Milorad Radović, sw67/2017

**Asistenti**
Dragan Vidaković, 
Milica Škipina

**Definicija problema**
Cilj projekta je detekcija nošenja zaštitnih maski u realnom vremenu. Ulaz u sistem predstavlja video snimak ljudi sa maskama ili bez maski. Izlaz iz sistema je filtriran video snimak, odnosno skup slika,  na kojoj su crvenom bojom uokvireni ljudi koji ne nose masku, a zelenom oni koji je nose.

**Motivacija zašto vredi rešavati dati problem**
Usled epidemije Korona virusa krajem 2019. godine svet je počeo rapidno da se menja. Iako je veliki broj aktivnosti prešao u online režim rada, još uvek postoje one za koje to nije moguće.
Zaštitne maske, kao način prevencije širenja virusa, postale su jedan od obeležja epidemije. Ljudi su u obavezi da nose maske u zatvorenom, dok ta praksa na otvorenom prostoru još uvek nije zastupljena. 
Ukoliko bi zaštitne kamere na ulasku u objekte koristile ovaj softver, te bi se omogućilo prepoznavanje da li se prilikom ulaska u objekat poštuju pravila nošenja zaštitnih maski. 
Ovo bi pomoglo u otkrivanju lica koja ne nose masku pri ulasku u objekat, te se naknadno može aktivirati alarm ili na neki drugi način obavestiti dežurno lice. Na taj način softver bi pomogao u zaštiti života i sprečavanju širenja virusa.

**Skup podataka**
Na [linku ](https://www.kaggle.com/andrewmvd/face-mask-detection) se nalazi skup podataka koji bismo koristili ali zbog nedovoljnog broja podataka moramo da ga proširimo.
Na [linku ](https://drive.google.com/file/d/18R5-8T26ctmX8qDPhNmM2xU2WNj2xUr_/view) se nalaze podaci koji su već prošli kroz proces augmentacije (na slikama su ljudi bez maske i oni kojima je maska veštački stavljena), te bismo ih korisliti kao dopunu na prvi skup podataka.
Na [linku ](https://www.kaggle.com/adityaaggarwal09/face-detection) se nalaze samo lica bez maski gde bismo mi vršili augmentaciju i preradu podataka kao što je urađeno na prethodno opisanom skupu podataka. Potom bismo ih takođe ubacili u skup podataka, ukoliko to bude bilo neophodno za bolje rezultate.

**Metodologija**
Pre samog rada sa konvolutivnim neuronskim mrežama potrebno je pretprocesirati podatke i tu je potrebno izdvojiti video u skup frejmova odnosno slika na kojima će se dalje raditi treniranje i obeležavanje. Po uzoru na radove koje smo pročitali prilikom traženja literature zaključili smo da bi ovakav sistem mogao biti dizajniran iz dve komponente. Prva komponenta je ekstraktor bitnih osobina koji je baziran na ResNet-50 modelu dubokog učenja. Druga komponenta koja se koristi za detekciju zaštitne maske koja je bazirana na YOLO v2 modelu. Za treniranje bismo koristili dva skupa podataka koji su navedeni iznad. Takođe nakon istraživanja ćemo utvrditi da li možemo da upotrebimo transfer learning, ukoliko pronađemo odgovarajući istreniran model.

**Evaluacija**
Skup podataka bismo razdvojili na trening skup, validacioni skup i test skup. Nakon treniranja modela na test skupu možemo evaluirati dati model pomoću metrika i zaključiti koja najbolje opisuje model. Metrika koja bi se koristila za evaluaciju uspešnosti verovatno bi bila average precision i log-average miss rate. Pomoću ovih metrika ćemo videti koji optimizacioni algoritam daje najbolju uspešnost. Osim samih metrika pokušali bismo da naš kroz algoritam pustimo demo video snimak i na njemu analiziramo uspešnost samog modela, odnosno broj dobro i loše prepoznatih objekata.

**Comment by Vukeezy** [comment]
**Tim**
Vukašin Ocokoljić, sw60/2017
Romana Erdelji, sw58/2017
Milorad Radović, sw67/2017

**Asistenti**
Dragan Vidaković, 
Milica Škipina

**Definicija problema**
Ulaz u sistem predstavlja slika ljudi sa maskama ili bez maski. Izlaz iz sistema je filtrirana slika na kojoj su crvenom bojom uokvireni ljudi koji ne nose masku, a zelenom oni koji je nose.

**Motivacija zašto vredi rešavati dati problem**
Usled epidemije Korona virusa krajem 2019. godine svet je počeo rapidno da se menja. Iako je veliki broj aktivnosti prešao u online režim rada, još uvek postoje one za koje to nije moguće.
Zaštitne maske, kao način prevencije širenja virusa, postale su jedan od obeležja epidemije. Ljudi su u obavezi da nose maske u zatvorenom, dok ta praksa na otvorenom prostoru još uvek nije zastupljena. 
Ukoliko bi zaštitne kamere na ulasku u objekte koristile ovaj softver, te bi se omogućilo prepoznavanje da li se prilikom ulaska u objekat poštuju pravila nošenja zaštitnih maski. 
Ovo bi pomoglo u otkrivanju lica koja ne nose masku pri ulasku u objekat, te se naknadno može aktivirati alarm ili na neki drugi način obavestiti dežurno lice. Na taj način softver bi pomogao u zaštiti života i sprečavanju širenja virusa.

**Skup podataka**
Na linku se nalazi skup podataka koji bismo koristili ali zbog nedovoljnog broja podataka moramo da ga proširimo.
Na linku se nalaze podaci koji su već prošli kroz proces augmentacije (na slikama su ljudi bez maske i oni kojima je maska veštački stavljena), te bismo ih korisliti kao dopunu na prvi skup podataka.
Na linku se nalaze samo lica bez maski gde bismo mi vršili augmentaciju i preradu podataka kao što je urađeno na prethodno opisanom skupu podataka. Potom bismo ih takođe ubacili u skup podataka, ukoliko to bude bilo neophodno za bolje rezultate.

**Metodologija**
Po uzoru na radove koje smo pročitali prilikom traženja literature zaključili smo da bi ovakav sistem mogao biti dizajniran iz dve komponente. Prva komponenta je ekstraktor bitnih osobina koji je baziran na ResNet-50 modelu dubokog učenja. Druga komponenta koja se koristi za detekciju zaštitne maske koja je bazirana na YOLO v2 modelu. Za treniranje bismo koristili dva skupa podataka koji su navedeni iznad. Takođe nakon istraživanja ćemo utvrditi da li možemo da upotrebimo transfer learning, ukoliko pronađemo odgovarajući istreniran model.

**Evaluacija**
Skup podataka bismo razdvojili na trening skup, validacioni skup i test skup. Nakon treniranja modela na test skupu možemo evaluirati dati model pomoću metrika i zaključiti koja najbolje opisuje model. Metrika koja bi se koristila za evaluaciju uspešnosti verovatno bi bila average precision i log-average miss rate. Pomoću ovih metrika ćemo videti koji optimizacioni algoritam daje najbolju uspešnost.

**Comment by vdragan1993** [comment]
U delu **Skup podataka** nedostaju spomenuti linkovi.

**Comment by Vukeezy** [comment]
> U delu **Skup podataka** nedostaju spomenuti linkovi.

Nažalost su nestali linkovi prilikom kopiranja iz dokumenta. Sada su dodati.

**Comment by vdragan1993** [comment]
Pošto se tim sastoji od tri člana, predlažemo sledeće:
1. da se projekat proširi tako da radi detekciju na videu
2. da se tim redukuje na 2 člana ukoliko se funkcionalnost ne bi menjala (da radi detekciju sa slike).

Vašu konačnu odluku (kada je donesete) napišite u sledećem komentaru.

**Comment by Vukeezy** [comment]
Prihvatamo prvu opciju da se projekat proširi tako da radimo detekciju na videu. Da li je potrebno da menjamo predlog projekta u odnosu na ovu izmenu?

**Comment by vdragan1993** [comment]
Zamolio bih vas da korigujete predlog projekta u skladu s izmenom.

**Comment by Vukeezy** [comment]
Poštovani,

Izmenili smo predlog projekta u skladu sa sugestijama.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Vukeezy** [comment]
Link ka repozitorijumu: https://github.com/Vukeezy/FaceMaskDetection
