### ISSUE TITLE
Detekcija šake i prepoznavanje kategorije i broja reči u igri Pantomime

### ISSUE THREAD

**Issue by evaj10** [ftn-ai-lab/sc-2020-siit#10]
### Tim:
Ksenija Prćić, SW10/2017
Eva Janković, SW18/2017

### Asistent:
Dragan Vidaković

## Definicija problema
Prepoznavanje različitih kategorija pojmova koje susrećemo prilikom igranja pantomime u realnom vremenu.
Ulaz u sistem predstavlja video zapis. Softver treba da obezbedi detekciju šaka i klasifikaciju njihovih položaja i pokreta u određene klase. Na osnovu prepoznate klase, izlaz sistema bi bila prepoznata kategorija pojma ili broj reči koji opisivani pojam sadrži.

## Skup podataka
Skup podataka bi bio kreiran ručno. Sastojao bi se od video zapisa koji prikazuju oznake konkretnih kategorija pojmova, kao i od video zapisa koji prikazuju broj reči pojma (podignut odgovarajući broj prstiju jedne ili obe šake).
Kategorije koje dolaze u obzir su (uz mogućnost proširenja u toku rada):
* Knjiga
* Film
* Serija
* Pozorišna predstava
* Fraza
Skup podataka bi bio dodatno uvećan primenom augmentativnih metoda.

## Metodologija
Metodologija za rešavanje ovog problema se deli na dva dela.

**Prva faza: Detekcija šake**
Prepoznavanje šake bi se radilo primenom maske u opsegu boje kože koja bi trebala da izdvoji šaku od pozadine.

**Druga faza: Klasifikacija položaja i pokreta šake**
Za klasifikaciju bi se najverovatnije koristila CNN, ali bismo takođe imali želju da probamo kako bi se LSTM mreža pokazala u vidu performansi i preciznosti.

## Evaluacija
Kreiran skup podataka bi bio podeljen na trening, validacioni i testni skup.
Pošto bismo sami kreirali skup podataka, trudili bismo se da odnos između zastupljenih klasa bude ujednačen. Iz tog razloga bismo koristili *accuracy* metriku.
Takođe, pošto se klasifikacija radi u realnom vremenu, bitno će nam biti i vreme odziva sistema.

## Repozitorijum
https://github.com/ksenija10/SC-Charades-10

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
