### ISSUE TITLE
Detekcija brojeva i rešavanje igre Moj broj - Slagalica

### ISSUE THREAD

**Issue by fmilica** [ftn-ai-lab/sc-2020-siit#11]
### Tim:
Milica Filipović, SW17/2017
Igor Lukić, SW53/2017

### Asistent:
Dragan Vidaković

## Definicija problema
Prepoznavanje svih cifara u okviru igre Moj broj, njihovo grupisanje:
* Broj koji treba izračunati
* Brojevi koji se koriste u računu
* * 4 jednocifrena broja
* * 2 višecifrena broja

i generisanje optimalnog rešenja pomoću prepoznatih brojeve, računskih operacija _(+, -, *, /) i zagrada_.
Takođe, ceo proces mora biti završen u predefinisanom vremenskom roku (trajanje same igre).
Ulaz u sistem predstavlja jedna fotografija, dok je izlaz sistema izraz kojim se dobija optimalno rešenje.

## Skup podataka
Skup podataka će biti kreiran ručno, kreiranjem *screenshot*-ova igre Moj broj, kao i fotografisanjem ekrana. Cilj korišćenja dva izvora jeste povećanje raznovrsnosti osvetljenja, uglova i kvaliteta fotografija koje dolaze na ulaz sistema.

## Metodologija
Rešavanje problema se deli u 2 etape:

1. **OCR - prepoznavanje cifara i njihovo grupisanje u brojeve**
Za prepoznavanje cifara će se koristiti thresholding za izdvajanje regiona od interesa od pozadine, kao i detekcije kontura samih brojeva. Za grupisanje cifara u brojeve će se koristiti algoritam za *cluster*-ovanje, najverovatnije KMeans.
2. **Generisanje izraza**
Probaćemo više različitih algoritama na bazi veštačke inteligencije i, poređenjem njihovih performansi, odlučićemo se za najpogodniji za naš problem.

## Evaluacija
Pošto se sam problem sastoji iz 2 raznolike etape, merilo uspešnosti koje ćemo koristiti zavisi od same etape.
1. **Prva etapa**
Akcenat je tačno prepoznavanje svih cifara (_character level accuracy_) i grupisanje istih u brojeve (_word level accuracy_). Proveravanje uspešnosti radićemo poređenjem prepozantih cifara i brojeva sa tačnim vrednostima zapisanim u tekstualnim fajlovima.
2. **Druga etapa**
Uspešnost određujemo na osnovu koliko je izračunata vrednost bliska traženoj, kao i na osnovu brzine dolaska do te vrednosti. Prednost ćemo dati sporijim rešenjima koja su bilža tačnoj vrednosti, ukoliko "upadaju" u vremensko ograničenje.

## Git repository
https://github.com/cigor99/MojBroj

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by cigor99** [comment]
Hvala, ovo je link ka repozitorijumu
https://github.com/cigor99/MojBroj
