### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by aleksag12** [ftn-ai-lab/sc-2020-siit#12]
**Tim**
Jelena Cupać SW13/2017
Aleksa Goljović SW14/2017

**Asistent**
Milica Škipina

**Definicija problema**
Cilj projekta je davanje smislenih odgovora na korisnikove poruke u realnom vremenu. Korisnik ne treba da bude svestan da razgovara sa _chatbot_-om već sa pravom osobom.

**Motivacija zašto vredi rešavati ovaj problem**
Danas je _chat_ najučestaliji vid komunikacije. Ovaj vid komunikacije je znatno dinamičniji od _email_ komunikacije, takođe, korisnici će pre odabrati ovaj vid komukacije (_chat_) u odnosu na druge vidove (telefonski pozivi, _email_...) radi dobavljanja dodatnih informacija.

**Metodologija**
Prvi korak u realizaciji _chatbot_-a je dobavljanje skupa podataka. Podatke je, zatim, potrebno pretprocesirati i to uključuje sledeće:
1. Konvertovanje svih poruka u _lowercase_ ili _uppercase_ kako algoritam ne bi tretirao različito iste reči.
2. Tokenizacija
3. Uklanjanje nestandarnih karaktera
4. Uklanjanje "_stop words_" (učestalih reči koje nemaju uticaj na rečenicu)
5. Lematizacija

Pretprocesiranje podataka biće urađeno pomoću _NLTK_ biblioteke.
Implementacija _chatbota_ se zasniva na koder-dekoder arhitekturi. Koristićemo _TensorFlow_ biblioteku za implementaciju _seq2seq_ modela koji se sastoji od _RNN_.

**Skup podataka**
Skup podataka bi bio preuzet sa [linka](https://www.kaggle.com/thoughtvector/customer-support-on-twitter). Ovaj skup podataka broji preko 3 miliona tvitova i odgovara na iste u vezi sa korisničkom podrškom najvećih brendova (_Apple_, _Amazon_, _Uber_...).

**Evaluacija sistema**
Skup podataka ćemo podeliti na trening, validacione i testne podatke u odnosu 80:10:10. Metrika koju bismo koristili za evaluaciju sistema je _loss_. Kako na istu poruku može da postoji više smislenih odgovara, tačnost bismo utvrdili samostalnom validacijom.

**Repozitorijum**
https://github.com/jelenac11/SoftKompjuting-projekat

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
