### ISSUE TITLE
Face detection and recognition

### ISSUE THREAD

**Issue by alenm10** [ftn-ai-lab/sc-2020-siit#13]
1.Tim: Alen Mujo, SW-1-17

2.Asistent: Dragan Vidaković

3.Definicija problema: Prepoznavanje lica je metoda identifikovanja ili verifikacije identiteta pojedinca pomocu njegovog lica. Sistemi za prepoznavanje lica se mogu koristiti za identifikaciju ljudi na fotografijama, video snimcima ili u stvarnom vremenu. U projektu ce biti odradjena detekcija lica sa slika i prepoznavanje detektovanog lica koriscenjem vise razlicitih metoda objasnjenih u 5. Ulaz u program je slika na kojoj se nalazi osoba a izlaz je ime prepoznate osobe.

4.Skup podataka: (FDDB: Face Detection Data Set and Benchmark) - http://vis-www.cs.umass.edu/fddb/ - Skup slika anotiranih imenima osoba koje su na slikama i nekoliko video snimka anotiranih na isti nacin

5.Metodologija: Resavanje problema detekcije i prepoznavanje lica ukljucuje:
  1. Detekciju lica i izdvajanje detektovane regije
  - dlib library
  - mtcnn library
  2. Feature extraction
  - FaceNet
  - Custom CNN 
  3. Feature matching
  - SVC()
  - LogisticRegression(),
  - RandomForestClassifier(),
  - kNN()

6.Evaluacija: poredjenje vise razlicitih kombinacija navedenih metoda : (accuracy, confusion matrix)

**Comment by vdragan1993** [comment]
Zamolio bih da korigujete predlog tako da prati **Sadržaj predloga projekta** koji je prezentovan na vežbama.

**Comment by alenm10** [comment]
.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by alenm10** [comment]
https://github.com/alen1010/face-detection-and-recognition_sc
