### ISSUE TITLE
Prepoznavanje slova i pronalaženje najduže reči u igri na slovo na slovo (Slagalica)

### ISSUE THREAD

**Issue by senpai132** [ftn-ai-lab/sc-2020-siit#15]
### Tim:
Aleksandar Nikolić, SW27/2017
Milan Jokanović, SW28/2017

### Asistent:
Dragan Vidaković

### Definicija problema
Prepoznavanje svih slova (12) u igri na slovo na slovo u kvizu "Slagalica". Potom će na osnovu prepoznatih slova pronaći najdužu smislenu reč na srpskom jeziku.
Ulaz u sistem predstavlja fotografija, dok je izlaz nadjuža pronađena reč.
Program će morati završiti pre isteka vremena same igre.

### Skup podataka
Kreiran ručno, slikanjem ekrana ove igre.

### Metodologija
Program će imati 2 faze:

    1. OCR - prepoznavanje slova
    2. Pronalaženje najduže reči (pomoću stabla pretrage)

### Evaluacija
Proveravaćemo tačnost prepoznavanja slova pomoću test skupa, a tačnost najdužeg rešenja tako sto ćemo pustiti program da radi sa slovima iz prethodnih epizoda "Slagalice" i porediti njihovo rešenje sa našim.

**Comment by vdragan1993** [comment]
Za najveću ocenu, fotografije moraju biti slikane pod različitim uglovima, osvetljenjem i rastojanjem od kamere.
Da li je to u redu?

**Comment by senpai132** [comment]
Jeste

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by senpai132** [comment]
Link repozitorijuma: https://github.com/milanjokanovic/Soft-kompjuting-projekat
Napomena: Moguće da će biti problema ako pokušate da pokrenete kod vas na računaru zato što na gitu nisu podržana srpska latinična slova (bar u txt fajlovima, ili mi nismo uspeli da namestimo encoding na git-u)
