### ISSUE TITLE
Detekcija podataka sa kreditne kartice

### ISSUE THREAD

**Issue by vukovic98** [ftn-ai-lab/sc-2020-siit#16]
# Tim

 Vladimir Vuković, SW3/2017
 Ivana Vlaisavljević, SW78/2017
 Dušan Madžarević, SW9/2017
###
--------------------------------------------------------
# Asistenti

 Dragan Vidaković
###
--------------------------------------------------------
# Definicija problema

 Cilj projekta je detekcija podataka kreditne kartice sa slike. Ulaz u sistem predstavlja slika kreditne kartice, dok izlaz iz sistema predstavljaju podaci o broju kartice, vlasniku kartice i godini važenja kartice, kao i forma transakcije popunjena podacima o uplatiocu.
###
--------------------------------------------------------
# Motivacija zašto vredi rešavati dati problem

 Rešavanje ovog problema bi dosta doprinelo zadovoljstvu korisnika ustanova koje se bave novčanim transakcijama (pošte, banke, menjačnice..). Ukoliko bi se rešenje ovog tipa integrisalo u sistem neke od ustanova povećala bi se brzina rada zaposlenih (npr. Integracija ovog resenja sa sistemom ustanove koja se bavi transakcijama bi omogućila brži rad automatskim popunjavanjem podataka o uplatiocu).    
###                                      
 Pored toga, ukoliko se sistem pokaže pouzdan, podaci sa kartice bi se mogli koristiti za dosta provera pri plaćanju, a neke od njih su fraud detection, provera validnosti kartice, detekcija tipa kartice itd..
###
--------------------------------------------------------
# Skup podataka

 Skup podataka će biti kreiran ručno, prikupljanjem slika kreditnih kartica sa interneta, kao i fotografisanjem. Cilj ovakvog načina prikupljanja podataka je povećanje raznovrsnosti slika u smislu osvetljenja, orijentacije kartice, zamućenja slike, itd..
###
--------------------------------------------------------
# Metodologija

 Ovaj problem spada u oblast OCR-a, pa ćemo koristiti Tesseract OCR za detekciju i prepoznavanje podataka.
Takođe, za prepoznavanje teksta na kartici će biti korišćen thresholding radi ekstrakcije regiona od interesa sa slike.
###
--------------------------------------------------------
# Evaluacija
 Skup podataka biće podeljen na podatke za treniranje, podatke za validaciju i podatke za testiranje. Pored accuracy vrednosti validacionog skupa, koristićemo i tekstualni fajl koji sadrži tačne podatke kartica testnog skupa za proveru uspešnosti očitavanja.
###

**Comment by vdragan1993** [comment]
Projekat nema dovoljnu složenost za najveću ocenu za tim od tri člana. 
Da li ćete:
1. Ipak raditi ovaj projekat?
2. Korigovati prijavu?
3. Prijaviti drugu temu?

**Comment by vukovic98** [comment]
Poštovanje,

Prijavićemo drugu temu u toku dana.

Pozdrav

Hvala unapred,
Vladimir Vuković SW3/2017
________________________________
