### ISSUE TITLE
Automatsko rešavanje rubikove kocke

### ISSUE THREAD

**Issue by miljanic** [ftn-ai-lab/sc-2020-siit#17]
## Tim
Miloš Miljanić, SW-86/2016

## Asistent
Dragan Vidaković

## Definicija problema
Navigacija korisnika prilikom rešavanja rubikove kocke. Kocka je snimana kamerom, a pored nje se korisniku prikazuju i potrebni potezi kako bi se ona resila.

## Skup podataka
Direktno će se raditi na videu sa kamere.
Pored toga, zarad lakseg testiranja postojaće i nekoliko ručno snimljenih videa rubikove kocke.

## Metodologija
1. Detekcija i skeniranje trenutnog stanja kocke (korišćenjem opencv biblioteke)
2. Korišćenje gotovih algoritama za rešavanje rubikove kocke.
3. Prikazivanje instrukcija za rešavanje.

## Evaluacija
Empirijski. Na kraju svakog izvršenog programa rubikova kocka bi trebalo da bude rešena.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by miljanic** [comment]
https://github.com/miljanic/rubiks-cube-solver
