### ISSUE TITLE
Detekcija cifara sa displeja aparata za točenje goriva

### ISSUE THREAD

**Issue by marijakas** [ftn-ai-lab/sc-2020-siit#18]
**Tim**
Ana Mirkov SW72/2017
Marija Kastratović SW43/2017

**Asistent**
Dragan Vidaković

**Definicija problema**
Cilj projekta je detekcija cifara koje predstavljaju količinu litara goriva sipanih u vozilo. 
Ulaz u sistem predstavlja slika displeja aparata za točenje goriva. Izlaz iz sistema je podatak o sipanoj količini goriva.

**Motivacija zašto vredi rešavati ovaj problem**
Cilj je napraviti softver koji omogućava da se na osnovu prepoznate količine sipanog goriva proračuna cena. Ta cena se dalje može koristiti u okviru sistema online plaćanja. 

**Skup podataka**
Skup podataka bi bio preuzet sa linka: https://www.kaggle.com/prathamjindal/digital-meter?fbclid=IwAR3PsjTg6Pb35XuNawbctO46TQj8bKHCPua6wlCjKqCoBZN5mIAJK2KLsJc

**Metodologija**
Koristićemo Python, OpenCV biblioteku za učitavanje ulazne slike, kao i za osnovne operacije nad učitanom slikom. 
Za optičko prepoznavanje karaktera koristićemo OCR. Neuronsku mrežu ćemo obučiti na trening podacima i kasnije kao takvu korisiti za testiranje.

**Evaluacija sistema**
Iz priloženog skupa podataka biće izdvojen deo podataka koji će se koristiti za treniranje, deo koji ćemo koristiti za verifikaciju i deo za testiranje obučene neuronske mreže. 
Kao meru performanski koristićemo tačnost-accuracy. Takođe, koristićemo datoteku koja sadrži tačne podatke za proveru učitanih podataka.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by mirkovana** [comment]
https://github.com/mirkovana/soft
