### ISSUE TITLE
Prepoznavanje muzičkog instrumenta i visine tona

### ISSUE THREAD

**Issue by marijacurcic7** [ftn-ai-lab/sc-2020-siit#19]
### **Tim**
Jovana Kostreš, SW51/2017
Marija Ćurčić, SW24/2017

### **Asistent**
Dragan Vidaković

### **Definicija problema**
Prepoznavanje visine tona i instrumenta kojim je taj ton odsviran. Na ulazu je .wav datoteka koja sadrži zvuk nekog instrumenta u određenom muzičkom tonu. Dat je ograničen skup instrumenata koji će se pojavljivati. Pored instrumenta, potrebno je odrediti ton u muzičkoj lestvici i oktavu kojoj pripada. Primer izlaza: Violin, D#4

### **Motivacija problema**
Rešenje ovog problema može se upotrebiti u muzičkoj transkripciji.

### **Skup podataka**
Za skup podataka koristile bismo [TinySOL](https://zenodo.org/record/3685367#.X_nkE-hKiMo) i/ili [UIOWA:MIS](http://theremin.music.uiowa.edu/MIS.html).

### **Metodologija**
Za obradu zvuka koristićemo biblioteku LibROSA. 
Osobina zvuka bismo izdvojile pomoću MFCCs.
Za klasifikaciju i trening koristile bismo više različitih CNN mreža, i izabrale onu koja daje najbolje rezultate.
U slučaju da su nam podaci neizbalansirani, koristile bismo Python-ovu biblioteku Imbalanced-learn.

### **Evaluacija**
Skup podataka ćemo podeliti na skupove za trening, test i validaciju. Efikasnost bismo odredile korišćenjem metrika accuracy i loss.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by marijacurcic7** [comment]
https://github.com/marijacurcic7/SC-Projekat
