### ISSUE TITLE
Kontrolisanje Photoshop alata pokretima prstiju preko web kamere

### ISSUE THREAD

**Issue by natasa-ivanovic** [ftn-ai-lab/sc-2020-siit#2]
<h2>Definicija problema</h2>

Kontrolisanje Photoshop grafičkog alata pokretima prstiju u realnom vremenu. Ključne funkcionalnosti našeg softvera bi podrazumevale manipulaciju kursorom (pomeranje i klik), crtanje četkicom (brush tool) i brisanje (eraser tool). Neke od Photoshop-ovih funkcionalnosti koje ćemo takođe razmotriti i potencijalno uključiti u program su zoom in/out, pan, select i transform. Različiti hand gestures bi trigerovali različite akcije - npr. samo ispružen kažiprst bi aktivirao brush tool, tj. crtanje.

<h2>Motivacija zašto vredi rešavati dati problem</h2>

Korišćenje grafičkog alata podrazumeva upotrebu različite tehničke opreme:
1. **miš** - često nedovoljno precizan, predstavlja otežavajući faktor za digitalno crtanje, ali je ujedno jedan od osnovnih delova računarske opreme koji skoro svako ima
2. **grafičke table** - često vrlo skupe, ali pružaju dobar user experience i intuitivniju kontrolu softvera

Najprirodniji način crtanja uključuje direktno korišćenje prstiju i softver koji bi to omogućio  značajno bi poboljšao kvalitet interakcije čoveka sa računarom, jer bi manipulacija grafičkim alatom bila moguća bez korišćenja eksternih uređaja.

<h2>Metodologija</h2>

Pre rada sistema potrebno je "iscrtati" validan prostor u kome bi se detektovali pokreti šake, koji je ekvivalentan radnoj površini u Photoshop-u. 
Ulaz u sistem predstavlja jedan video frejm. Obrada tog frejma bi se odvijala na sledeći način:

**Prva faza: Detekcija šake i pretprocesiranje**
1. Izdvajanje od pozadine 
2. Thresholding za pronađeni region od interesa
3. Detekcija kontura 
4. Pronalaženje ključnih tačaka (centar šake i kažiprst)

**Druga faza: Utvrđivanje položaja šake u cilju trigerovanja odgovarajuće akcije**
1. CNN za utvrđivanje stanja

**Treća faza: Sprovođenje akcije u Photoshop alatu**
1. Translacija koordinata tačke kažiprsta na odgovarajući deo radne površine
2. Primena akcije

<h2>Skup podataka</h2>
Trenirali bismo CNN nad skupom podataka koji bismo sami napravili - sastojao bi se samo od onih hand gestures koje bismo izabrali za manipulaciju alatom, a zatim bismo primenom augmentacije uvećali taj skup podataka. Nad svim slikama bismo primenili pretprocesiranje (izdvajanje od pozadine i thresholding) kako bismo donekle izbegli osetljivost mreže na osvetljenje i pozadinu.

<h2>Evaluacija</h2>
Naš skup podataka bismo podelili na trening, validacioni i testni skup u odnosu 80:10:10. Metrike koje bismo koristili za evaluaciju CNN bi bile accuracy i loss.
Evaluacija rada celog sistema bi se svela na to koliko je korisnik zadovoljan odzivom sistema, odn. koliko brzo/efikasno je uspeo da sprovede akcije koje je želeo.

<h3>Asistent</h3>
Dragan Vidaković

<h3>Tim</h3>
Mario Kujundžić, SW59/2017<br>
Nataša Ivanović, SW47/2017

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by natasa-ivanovic** [comment]
[Link do repozitorijuma](https://github.com/natasa-ivanovic/photoshop-handler)
