### ISSUE TITLE
Detekcija registarskih tablica na videu

### ISSUE THREAD

**Issue by vukovic98** [ftn-ai-lab/sc-2020-siit#20]
# Tim
Vladimir Vuković, SW3/2017
Ivana Vlaisavljević, SW78/2017
Dušan Madžarević, SW9/2017

# Asistenti
Dragan Vidaković

# Definicija problema
Cilj projekta je detekcija registarskih oznaka vozila na videu.

# Motivacija zašto vredi rešavati dati problem
Rešenja ovog tipa su dosta korisna u mnogim oblastima. Na primer kod parkinga-za automatsko očitavanje registarskih oznaka vozila pri ulasku i izlasku sa parkinga, u kriminologiji za detektovanje registarskih oznaka vozila koja su se našla na mestu zločina, a snimljena su kamerama za nadzor koje se nalaze na okolnim objekatima, u saobraćaju, itd..

# Skup podataka
Skup podataka ce se kreirati ručno prikupljanjem videa vozila sa interneta.

# Metodologija
Pre nego što se počne sa prepoznavanjem oznake registarskih tablica, potrebno je podeliti video na frejmove, odnosno slike i augmentaciju tih slika radi boljeg raspoznavanja bitnih regiona, i to koristeći OpenCV biblioteku. Nakon toga, pomoću Hough transformacije bismo pronašli tablicu na fotografiji i nakon toga upotrebom OCR-a detektovali slova (A-Z) i cifre (0-9) sa tablice.

# Evaluacija
Evaluacija preciznosti rešenja utvrđivaće se poređenjem očitanih vrednosti oznake registarske tablice sa istinitim vrednostima upisanim u tekstualni fajl.

# Repozitorijum
https://github.com/vukovic98/soft_computing

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
