### ISSUE TITLE
Klasifikacija zvuka iz okruženja pomoću dubokih konvolutivnih neuronskih mreža

### ISSUE THREAD

**Issue by djuricmilan** [ftn-ai-lab/sc-2020-siit#21]
**Tim:**
Milan Đurić, SW 12-2017

**Asistenti**
Milica Škipina

**Definicija problema**
Cilj projekta jeste da se kreira sistem koji će na osnovu ulaznog zvučnog signala izvršiti klasifikaciju na jednu od 10 kategorija: _lajanje psa, helikopter, pucketanje vatre, motorna testera, beba koja plače, kiša, otkucaji sata, petao, morski talasi i kijanje_

**Motivacija**
Tradicionalni pristupi rešavanja problema klasifikacije zvuka su često podeljeni u dva disjunktna dela:
1.  Izdvajanje osobina iz skupa podataka (feature engineering) radi kreiranja reprezentacije pogodne za rešavanje problema nadgledanog učenja
2.  Prediktivno modelovanje, odnosno izgradnja modela koji će izvršiti klasifikaciju

Proces feature engineering-a je često veoma izazovan i vremenski zahtevan. U oblasti klasifikacije zvuka, za ovaj proces se često koristi heuristika poznata kao Mel-frequency cepstrum koeficijenti ([MFCC](https://en.wikipedia.org/wiki/Mel-frequency_cepstrum#:~:text=Mel%2Dfrequency%20cepstral%20coefficients%20(MFCCs,%2Da%2Dspectrum%22).)) ali i neke jednostavnije heuristike kao što su [Zero crossing rate](https://en.wikipedia.org/wiki/Zero-crossing_rate) i Teager Energy Operator.  Dobijene reprezentacije često nisu dovoljno robusne i kada se primene zajedno sa nekim tradicionalnim metodom mašinskog učenja, poput Random Forest-a ili SVM-a, rezultat bude suboptimalan. 

Iz tog razloga se danas češće koriste konvolutivne neuronske mreže, koje su u stanju da same ekstrahuju potrebne osobine iz ulaznog spektograma ili sirovog audio signala.

**Metodologija**
U ovom projektu pokušali bismo da izvršimo klasifikaciju zvuka pomoću neuronskih mreža, za početak direktno na osnovu audio signala (jednodimenzionalnog vektora, 1D konvolutivni slojevi), bez ikakvog ručnog dizajniranja osobina ili posebno kreiranih spektograma. Zatim bismo isti problem pokušali da rešimo upotrebom MFCC-a na ulazu, ovog puta pomoću 2D konvolutivnih slojeva. U oba slučaja bismo eksperimentisali sa različitim arhitekturama (broj konvolutivnih slojeva, batch normalizacija, zamena potpuno spojenih slojeva sa GlobalAveragePooling-om...).

Takođe, na početku ćemo uraditi i eksplorativnu analizu podataka i neophodno predprocesiranje koje bi trebalo da doprinese robusnosti oba modela.

**Test skup**
Test podaci i više informacija o njima s [ovde](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YDEPUT).

**Evaluacija**
Za evaluaciju bismo koristili neku od standardnih metrika poput F1 mere, preciznost, odziv, i naravno tačnost. Rezultate bismo takođe analizirali na osnovu matrice konfuzije.

**Comment by milica-skipina** [comment]
Projekat nema dovoljnu složenost za najveću ocenu za tim od dva člana.
Da li ćete:

    1. Ipak raditi ovaj projekat?
    2. Korigovati prijavu?
    3. Prijaviti drugu temu?

**Comment by djuricmilan** [comment]
Poštovanje,

Odlučili smo ipak da se podelimo, kolega će prijaviti neku drugu temu. Da li je to u redu?

**Comment by milica-skipina** [comment]
Jeste.
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by djuricmilan** [comment]
[Repozitorijum](https://github.com/djuricmilan/sound-classification)
