### ISSUE TITLE
Klasifikacija novinskih članaka na srpskom jeziku

### ISSUE THREAD

**Issue by gegic** [ftn-ai-lab/sc-2020-siit#22]
**Tim**
Damjan Manojlović, SW20/2017
Haris Gegić, SW70/2017

**Asistent**
Dragan Vidaković

## Definicija problema
Potrebno je izvršiti određivanje kategorije članaka na osnovu opisa članka.
Ulaz predstavlja kratki pasus koji je u stvari opis članka na srpskom jeziku, dok se na izlazu nalazi procena naziva glavne teme kojoj članak pripada.

## Motivacija problema
Omogućeno je jednostavno gupisanje novinskih članaka na osnovu tematike o kojoj se u članku govori, što automatizuje i ubrzava proces pisanja članaka, dajući mogućnost da se grupisanje učini čak i nezavisnim od samog autora.

## Skup podataka
S obzirom na to da skup novinskih članaka uz pridružene kategorije ne postoji za srpski jezik, biće potrebno da se takav skup podataka prikupi sa interneta. 
Uz vođenje računa da se u skupu ne nađu senzacionalistički opisi (ŠOK, NEVEROVATNO i sl.), planira se da se skup podataka prikupi sa domaćih portala.
Tematika o kojoj se u vijesti može govoriti biće razdvojena u sljedeće kategorije:
Politika, Društvo, Ekonomija, Sport, 
Život i kultura, Auto, Nauka i tehnologija, Svijet.
<sub><sup>Članovi 43-46. Zakona o autorskim i srodnim pravima omogućavaju prikupljanje takvih podataka sa interneta.</sup></sub>

## Metodologija
Biće potrebno svesti sve riječi koje se ponavljaju u različitim oblicima na jedan isti oblik, te će u tekstu izvršiti tokenizacija i korenovanje (stemovanje), naravno, za srpski jezik. Biće izvršeno preračunavanje tf-idf za svaki tekst, da bi se onda izvršilo računanje verovatnoća kategorija korišćenjem Naive Bayes algoritma. 

## Evaluacija
Za evaluaciju će biti korišćene standardne Accuracy, Precision, Recall i F1 score metrike.

**Comment by vdragan1993** [comment]
Projekat nema dovoljnu složenost za najveću ocenu za tim od dva člana.
Da li ćete:
1. Ipak raditi ovaj projekat
2. Korigovati prijavu
3. Prijaviti drugu temu

?

**Comment by gegic** [comment]
S obzirom na to da nam manjak alata i podataka za rad sa srpskim jezikom ionako komplikuje izradu, nećemo korigovati prijavu već ćemo prijaviti drugu temu. 
Hvala
