### ISSUE TITLE
Klasifikacija likova u igrici na osnovu rase

### ISSUE THREAD

**Issue by JSTheGreat** [ftn-ai-lab/sc-2020-siit#23]
**Tim**
Jovan Svorcan SW 29/2017
Marko Mijatović SW 30/2017

**Asistenti**
Dragan Vidaković
Milica Škipina

**Definicija problema**
Cilj projekta je prepoznavanje rase likova iz igrice "The Elder Scrolls V: Skyrim".
Program treba da uzme sliku lica lika i da prepozna kojoj rasi u igrici taj lik pripada.
U igrici postoji ukupno 10 rasa.

**Skup podataka**
Za ovaj projekat bismo koristili slike koje bismo sami sakupili.

**Metodologija**
Koristićemo Python OpenCV biblioteku za učitavanje slika kao i za dalje operacije nad njima.
Za detekciju lica ćemo implementirati Haar cascade detection metodu pomoću predefinisanih klasifikatora OpenCV biblioteke.
Koristeći neuronske mreže ćemo prvi učitati slike sa trening skupa da klasifikujemo sve rase, a potom ćemo testirati
klasifikaciju na primerima sa test skupa.

**Evaluacija**
Skup podataka bismo podelili na trening i test. Kao meru performansi koristićemo tačnost-accuracy.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by JSTheGreat** [comment]
Link: https://github.com/Makim1998/sc-face_recognition_and_classification_in_skyrim
