### ISSUE TITLE
ADR(Animal Detection and Recognition)

### ISSUE THREAD

**Issue by filip13111998** [ftn-ai-lab/sc-2020-siit#24]
Tim
Vasić Filip ,sw39/2017,
Grk Ilija  ,sw2/2017.

Asistenti
Dragan Vidaković

Repo:
[ADR](https://github.com/filip13111998/Soft-Computing)

Definicija problema
Detekcija i prepoznavanje životinja na slikama. Na osnovu slike koju imamo na ulazu sistema aplikacija će uokviriti životinju/e ukoliko se nalazi na slici i zatim napisati kratak opis prepoznate vrste.

Skup podataka
Za skup podataka izabran je [animals 10 dataset](uhttps://www.kaggle.com/alessiocorrado99/animals10rl). Skup podataka još uvek nije konačan. Dataset sadrži slike životinja iz različitih uglova , različitih udaljenosti kao i u različitim vremenskim uslovima. Dataset će sadržati 10 vrsta životinja.

Metodologija
Probelm bi podelili u dve faze gde bi bi u prvoj fazi radili detekciju životinja upotrebom Sliding Windowa i Non Maxima Suppression algoritma a zatim bi klasifikaciju životinja radili upotrebom Custom CNN-a.

Evaluacija
Dataset koji čini preko 25 000 slika i biće podeljen u odnosu 80:20. Uspešnost validacije će biti evaluirana upotrebom accuracy i loss metrike na osnovu kojih bismo izabrali najpogodniju arhitekturu CNN-a za naš problem.

**Comment by vdragan1993** [comment]
Tema odobrena.
Srećan rad.
