### ISSUE TITLE
Detekcija Long Method i God Class code smellova na osnovu obilježja code2seq modela

### ISSUE THREAD

**Issue by permitt** [ftn-ai-lab/sc-2020-siit#27]

**Comment by permitt** [comment]
**Tim** 
Mitar Perović SW71/17

**Asistent** 
Dragan Vidaković

**Definicija problema**
Detekcija Long Method i God Class code smellova na osnovu obilježja iz code2seq modela.

**Dataset**
Koristiću [MLCQ dataset](https://zenodo.org/record/3590102#.X_4DL-hKiHt), verziju koja je sređena za potrebe CleanCaDET probjekta. Za neke sampleove postoji više različitih anotacija od strane različitih reviewera. Koristću labelu koja je rezultat većine vote-ova (majority) svih anotacija za dati kod.

Podjela na trening, validacioni i test skup. Proporcija : 80% za trening i 20% za test skup (za ML klasifikatore). Za ostale podjela 70% trening, 10% validacioni i 20% test skup (za neuronske modele, ako budu korišćeni kasnije). Pošto je dataset nebalansiran, tipa za long method proporcija non code smell vs code smell je otprilike 88% naspram 12%, primjeniću tehnike za balansiranje skupa podataka.

**Metodologija**
Postojala bi dva klasifikatora, po jedan za Long Method i God Class.
Ulaz u klasifikator (Random Forests, SVM,..) bi bio vektor iste dužine kao izlaz iz code2seq modela. Za Long Method bi samo proslijeđivao vektor ekstrahovan iz code2seq, dok bi za God Class taj vektor računali na neki način. Svaka metoda iz klase bi bila predstavljena vektorom a zatim bi tražili nekakvu kombinaciju tih vektora. Prvi pristup bi bio samo mean svake dimenzije svih vektora. 
Izlaz iz klasifikatora bi bio integer koji nam govori da li je u pitanju code smell ili ne. Tipa 0 za non code smell, i 1 za code smell.
Za evaluaciju bi koristio mikro F1 skor, precision i recall.
Na kraju bi bila odrađena analiza grešaka, da se vidi na konkretnim primjerima gdje klasifikatori prave greške, zbog čega dolazi do toga.

## Github  Repo
https://github.com/permitt/code-smeller

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
