### ISSUE TITLE
Detekcija i resavanje igre sudoku sa videa u realnom vremenu

### ISSUE THREAD

**Issue by matijapetrovic** [ftn-ai-lab/sc-2020-siit#28]
### Tim:
Matija Petrović, SW33/2017
Nikola Kabašaj, SW50/2017

### Asistent:
Dragan Vidaković

### Definicija problema
Detekcija i izdvajanje sudoku mreže, kao i prepoznavanje cifre ili praznog polja za svaku ćeliju. Nakon toga, rešavanje samog sudokua i prikaz rešenja u realnom vremenu.

### Skup podataka
Skup podataka će biti kreiran ručno, snimanjem videa na kojima će se nalaziti sudoku mreža koja nije rešena, kao i snimanjem ekrana na kojem se nalazi sudoku. Takođe će biti koriščen MNIST skup podataka za treniranje CNN-a za prepoznavanje brojeva.

### Metodologija

1. Prepoznavanje i izdvajanje sudoku mreže pomoću thresholding-a i aproksimacije kontura.
2. Transformacija perspektive kako bismo dobili sudoku mrežu u obliku kvadrata.
3. Izdvajanje i prepoznavanje brojeva i praznih ćelija pomoću istrenirane CNN mreže.
4. Rešavanje samog sudokua pomoću _backtracking_ algoritma.
5. Renderovanje rešenja i prikaz nazad u videu.

### Evaluacija
Evauliraćemo tačnost rešenja sudokua, koje će zavisiti od tačnosti prepoznavanja same sudoku mreže sa videa, kao i vreme koje je potrebno da se rešenje prikaže na videu.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by matijapetrovic** [comment]
https://github.com/matijapetrovic/real-time-sudoku-solver
