### ISSUE TITLE
Predefinisani projekat 3

### ISSUE THREAD

**Issue by nmikovic** [ftn-ai-lab/sc-2020-siit#29]
### Student 
Nemanja Miković SW68-2016
### Asistent
Dragan Vidaković
### Metodologija
Primenom tresholding tehnika želim da odvojim osobe koje se kreću i plato. Potrebno je detektovati ivice platoa (Canny + Hough transformacija  ) i nakon toga brojati prelaze osoba preko tih ivica.
### Repozitorijum
https://github.com/nmikovic/softProjekat

**Comment by milica-skipina** [comment]
Niste naveli asistenta kod kojeg ste pohađali vežbe.

**Comment by nmikovic** [comment]
> Niste naveli asistenta kod kojeg ste pohađali vežbe.

Greška je uklonjena
