### ISSUE TITLE
Klasifikacija ptica na osnovu zvuka

### ISSUE THREAD

**Issue by miki-lauda** [ftn-ai-lab/sc-2020-siit#3]
**Tim:** Marinković Milan SW57/2017
**Asistent**: Vidaković Dragan

### Definicija problema
Klasifikacija ptica na osnovu zvuka koji ptica emituje. Na ulazu je zvuk određenog trajanja, koji sadrži zvuk ptice, a na osnovu tog zvuka, sistem bi trebalo da na izlazu da koja je vrsta ptice u pitanju. Vršiće se klasifikacija šest vrsta ptica: golub, sova, vrabac, lasta, vrana i gavran. 

### Motivacija zašto vrijedi rješavati dati problem
Sistem bi mogao da se koristi u situacijama kada čujete zvuk određene ptice, a ne možete da je vidite, na lak način saznate koja je ptica u pitanju. Takođe, ptice ispuštaju različite zvukove u različitim situacijama ( kada upozoravaju na opasnost, kada love, kada „razgovaraju“, ...), te je teško znati sve moguće vrste zvukova koje svaka ptica može proizvesti. 

### Metodologija
Prvi korak u izradi ovog sistema bio bi prikupljanje potrebnog skupa podataka. 
Zvuk je zatim potrebno obraditi kako bi se izbacili pozadinski zvukovi i dobio što je moguće jasniji zvuk koji ptica emituje. To bih pokušao primjenom low-pass, high-pass filtera ili kombinacijom oba filtera, eventualno, primjenom nekih drugih metoda, ako bih ih otkrio pri izradi projekta. 
Takođe, zvukovi su različite dužine, te bih duže snimke podijelio na više zvukova određene dužine, gdje bih dužinu snimka odredio na osnovu rezultata koje bih dobijao. Biblioteka za rad sa zvukom koja će se koristiti je LibROSA.

Nakon toga bih izdvojio osobine zvuka pomoću MFCCs, rezultat je slika koja je ulaz u CNN mrežu. CNN mrežu bih pokušao sam da kreiram, ali i da upotrijebim neku od već postojećih mreža, pa da uporedim rezultate i odaberem najbolju. Izlaz iz sistema će biti predikcija vrste ptice čiji je zvuk bio na ulazu u sistem.

### Skup podataka
Podatke bih preuzeo sa [link ](https://www.xeno-canto.org/) za svaku vrstu ptice pojedinačno, ali tako da je skup podataka za svaku vrstu ptice ujednačen.

### Evaluacija sistema
Podatke bih podijelio na trening, validacione i testne podatke u omjeru 70:20:10. Metrike koje bih koristio za evaluaciju sistema bile bi accuracy i loss. Gdje bi accuracy predstavljao tačnost čitavog sistema. Dodatno bih mogao da uvedem F1, Recall i Precision, kako bih odredio tačnost sistema za svaku vrstu pojedinačno.

### Link do repozitorijuma
[link do repozitorijuma](https://github.com/miki-lauda/klasifikacija-ptica)

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
