### ISSUE TITLE
Formiranje i detekcija lažnih (deepfake) video zapisa

### ISSUE THREAD

**Issue by roki021** [ftn-ai-lab/sc-2020-siit#30]
**Tim**
Milan Pavlov SW35/2017
Sara Miketek SW62/2017
Vladimir Rodušek SW23/2017

**Asistent**
Dragan Vidaković

**Definicija problema**
Cilj projekta je da se izgradi rešenje koje bi formiralo “deepfake“ video zapise kao i rešenje koje bi detektovalo da li je video zapis lažan odnosno “deepfake“.

**Motivacija problema** 
Korišćenje “deepfake” video zapisa se koristi u dosta loše svrhe, pa bi fokus našeg projekta bio da napravimo rešenje koje detektuje takve video zapise, a pored toga bi smo napravili i rešenje koje bi formiralo navedene video zapise i na taj način bi bolje evaluirali samu detekciju. Ovo rešenje bi našlo dobru primenu u detekciji već navedenih “deepfake” video zapisa i time smanjilo zloupotrebu i krađu identiteta.

**Metodologija**
Metodologije koje bi koristili bi smo podelili u dva dela, jedan za formiranje, a drugi za samu detekciju lažnih video zapisa. Način rešavanja bi bio:
1. Korišćenjem generativnih kontradiktornih neuronskih mreža (GAN) bi smo formirali “deepfake” video zapise, odnosno korišćenjem MTCNN mreže bi se izdvajala lica iz video zapisa i dalje bi se radilo binarno maskiranje slika lica koje bi GAN mreža dalje koristila za treniranje i formiranje “deepfake” video zapisa,
2. Konvolutivne neuronske mreže bi se koristile pri detekciji, konkretno bi se oslanjali na “MesoNET” arhitekturu, koja koristi “Meso-4” i “MesoInception-4” konvolucione neuronske mreže.

**Evaluacija**
Formiranje samih video zapisa bi smo testirali našim rešenjem detekcije i time bi smo dobijali koliko je kvalitetno formiranje i sama detekcija, a samu detekciju bi dodatno evaluirali korišćenjem tačnosti odnosno “accuracy” prepoznavanja lažnih i originalnih video zapisa.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by roki021** [comment]
https://github.com/roki021/DeepFakeDetector
