### ISSUE TITLE
Prepoznavaje biljaka na osnovu lista

### ISSUE THREAD

**Issue by tamaraglisic** [ftn-ai-lab/sc-2020-siit#32]
**1. Tim**
Tamara Glišić sw38/2017
Snježana Simić sw82/2018
Nataša Kovačević sw81/2018

**2. Asistent**
Milica Škipina
Dragan Vidaković

**3. Definicija problema**
Ulaz u sistem bi bila fotografija biljke. Sistem bi na fotografiji detektovao list (listove) biljke. Na osnovu karakterističnih tačaka bi pronašao koja je vrsta biljke u pitanju, i pružio detalje koji se odnose na konkretnu biljku.

**4. Motivacija problema**
U svetu postoji oko 400,000 biljnih vrsta, a velika većina ljudi može prepoznati samo određeni broj biljaka. Ovaj sistem se može upotrebiti u složenijim sistemima gde bi korisnici mogli uslikati biljku i na brz način upoznati se sa biljkama oko sebe, i naučiti o njima sve što ih zanima.

**5. Skup podataka**
https://archive.ics.uci.edu/ml/datasets/leaf#
Ovo nije konačan skup podataka, ukoliko ne bude dao zadovoljavajuće rezultate, zamenićemo 
ga nekim širim skupom.
Za ulazne podatke ce biti korišćene ručno uslikane fotografije biljaka ili neki već postojeći skup fotografija koje sadrže više listova.
Skup podataka o taksonomskim kategorijama (carstvo, tip, klasa, familija...), koji će dati detaljnije informacije za svaku vrstu, biće napravljen ručno. Sadržaće podatke za svaku vrstu iz dataset-a.

**6. Metodologija**
Detekcija listova sa fotografije upotrebom adaptivnog threhold-a.
Za klasifikaciju biljke nepohodno je nad trening podacima izvršiti pretprocesranje
(grayscale, thresholding, otklanjanje sumova...), zatim pronaći osobine i uz pomć
SVM algoritma izvršiti klasifikaciju.

**7. Evaluacija**
Dataset će biti podeljen u odnosu 80:20. 80% podataka će biti iskorišćeno za trening, a 20% za testiranje. U tih 20%  svaka vrsta će imati podjednak udeo. 
Za detekciju lista od važnosti su nam parametri accuracy i time behavior jer se sistem može koristiti u realnom vremenu.
Kako na jednoj slici može biti više listova iste biljke (ili list sa strane koji možda ne pripada istoj biljci, a detektovan je), izlaz iz sistema će biti vrsta čiji list ima najveću tačnost.
Druga ideja je da će izlaz biti vrsta čijih je listova najviše pronađeno. Udeo te vrste (procenat) bi pokazivao tačnost čitavog sistema.
Isprobali bismo oba načina za evaluaciju čitavog sistema kako bi videli koji od ova dva pristupa je pouzdaniji.

**Repozitorijum**
[link](https://github.com/tamaraglisic/Soft-computing)

**Comment by milica-skipina** [comment]
Podaci o asistentima nisu dobro napisani.

Projekat nema dovoljnu složenost za najveću ocenu za tim od tri člana.
Da li ćete:

1. Ipak raditi ovaj projekat?
2. Korigovati prijavu?
3. Prijaviti drugu temu?

**Comment by tamaraglisic** [comment]
Proširili smo problem dodajući prethodno detekciju listova na slici, zatim određivanje vrste i na kraju prikaz informacija koje se odnose na konkretnu vrstu biljke.

**Comment by milica-skipina** [comment]
Korigujte evaluaciju tako što ćete dodati i metriku za evaluaciju detekcije.

**Comment by tamaraglisic** [comment]
> Korigujte evaluaciju tako što ćete dodati i metriku za evaluaciju detekcije.

Dodato.

**Comment by milica-skipina** [comment]
Korigujte definiciju problema kako bi bilo jasnije koji su ulazi i izlazi iz sistema.
U evaluaciji nije jasno definisano kako će biti evaluirano prepoznavanje biljke.

**Comment by tamaraglisic** [comment]
> Korigujte definiciju problema kako bi bilo jasnije koji su ulazi i izlazi iz sistema.
> U evaluaciji nije jasno definisano kako će biti evaluirano prepoznavanje biljke.

Korigovano.

**Comment by milica-skipina** [comment]
Definicija problema i evaluacija rješenja se ne podudaraju. U definiciji je navedeno da izlaz iz sistema predstavlja vrsta biljke i detalji vezani za nju, dok u evaluaciji još uvijek nije precizirano kao će nakon detekcije i klasifikacije listova biti utvrđeno o kojoj konkretnoj biljci je riječ. 
Korigujte evaluaciju.

**Comment by tamaraglisic** [comment]
> Definicija problema i evaluacija rješenja se ne podudaraju. U definiciji je navedeno da izlaz iz sistema predstavlja vrsta biljke i detalji vezani za nju, dok u evaluaciji još uvijek nije precizirano kao će nakon detekcije i klasifikacije listova biti utvrđeno o kojoj konkretnoj biljci je riječ.
> Korigujte evaluaciju.

Korigovano. Ovo su trenutne ideje za evaluaciju, koje u toku izrade projekta mogu biti prosirene, npr skaliranjem tačnosti prepoznatih listova iste vrste, pa bi u zavisnosti od tih rezultata bila odabrana konačna vrsta kao izlaz sistema.
Nadam se da smo Vas razumeli.

**Comment by milica-skipina** [comment]
Koja metrika će biti korištena za evaluaciju prepoznavanja vrste biljke?

**Comment by tamaraglisic** [comment]
> Koja metrika će biti korištena za evaluaciju prepoznavanja vrste biljke?

Accuracy, a izlaz sistema će se porediti sa istinitosnim vrednostima.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
