### ISSUE TITLE
Fitness aplikacija za izračunavanje nutritivnih vrednosti voća i povrća na slici

### ISSUE THREAD

**Issue by Quadrition** [ftn-ai-lab/sc-2020-siit#34]
### Tim

Veljko Plećaš SW68-2017
Ivana Marošević SW74-2017
Petar Cerović SW26-2017

### Asistenti
Dragan Vidaković

### Definicija problema
Cilj je da se detektuje količina nutritivnih vrednosti na slici. Potrebno je da se na slici detektuje svo voće i povrće koje se nalazi na njemu, odraditi njihovu klasifikaciju, i na osnovu rezultata i tablice o količini kalorija svakog voća/povrća odrediti ukupnu količinu nutritivnih vrednosti sa slike.

### Motivacija
Rešenje ovog problema može koristiti svim sportistima i ljudima koji vode računa o svojoj ishrani.

### Skup podataka
Za treniranje i testiranje neuronske mreže koristićemo [KAGGLE ](https://www.kaggle.com/moltean/fruits) skup podataka. Po potrebi ćemo priložiti još neke ručno sakupljene slike za validaciju.

### Metodologija

1. Za klasifikaciju podataka će se raditi treniranje konvolucionih neuronskih mreža nad relevantnim skupom podataka
2. Detekcija objekata na slici će se raditi upotrebom adaptivnog treshold-a

### Evaluacija
Za evaluaciju detekcije objekata koristićemo intersection over union uz pomoć koje ćemo videti koliko su detektovane regije precizne. Evaluacija klasifikacije objekata biće urađenja uz pomoć accuracy metrike (ili cross entropy loss) koja će nam određivati preciznost klasifikacije. Za rezultate nutritivnih vrednosti koristićemo Mean squared error metriku.

### GitHub repozitorijum
https://github.com/Ivana98/fitness-app-ai

**Comment by vdragan1993** [comment]
Korigujte evaluaciju rešenja tako što ćete umesto poređenja ubaciti metriku (ili više njih) greške (po vašem izboru) za poređenje stvarne i dobijene nutritivne vrednosti.

**Comment by Quadrition** [comment]
Korigovano

**Comment by vdragan1993** [comment]
Zašto se za evaluaciju klasifikacije koristi cross entropy loss, a ne neka metrika koja je "standardnija" za klasifikaciju (npr. tačnost ili f-mera) ?

**Comment by Quadrition** [comment]
Cross entropy loss smo stavili zbog optimizacije modela. Vratili smo i accuracy metriku, pa ćemo videti šta će nam biti pogodnije za evaluaciju. Ako moramo da izaberemo samo jedan, ostavićemo accuracy metriku.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Ivana98** [comment]
[Link do repozitorijuma.](https://github.com/Ivana98/fitness-app-ai)
