### ISSUE TITLE
Proizvoljan real-time neuronski prenos stila

### ISSUE THREAD

**Issue by kandicst** [ftn-ai-lab/sc-2020-siit#4]
**Tim:**
Stefan Kandić SW73-2017
**Asistent:**
Milica Škipina

## Definicija Problema
Neuronski prenos stila predstavlja tehniku mašinskog učenja za sintezu dve odabrane slike, jedne za sadržaj i druge za stil, tako da generisana slika zadrži sadržaj prve a primi stil druge slike.

<p align="center">
  <img width="700" src="https://www.researchgate.net/profile/Adar_Elad/publication/325467165/figure/fig1/AS:632315055202305@1527767065571/Gatys-et-al-Results.png"/>
</p>

## Metodologija
Prvi pristup rešavanju ovog problema ([Gatys _et al_](https://openaccess.thecvf.com/content_cvpr_2016/papers/Gatys_Image_Style_Transfer_CVPR_2016_paper.pdf)) se zasnivao na iterativnom minimizovanju razlike feature mapa generisane slike sa slikama stila i sadržaja pomoću pretrenirane VGG19 mreže. Metod je pokazao dobre rezultate, ali je zbog svoje iterativne prirode dosta spor jer je za konvergenciju potrebno više stotina iteracija od kojih svaka uključuje forward i backward pass kroz obimnu VGG mrežu.

Do poboljšanja se došlo treniranjem neuronske mreže tako da u jednom prolazu generiše izlaznu sliku ([Wang _et al_](https://arxiv.org/abs/1612.01895), [Ulzanov _et al_](https://arxiv.org/abs/1701.02096), [Dumoulin _et al_](https://arxiv.org/abs/1610.07629), [Li _et al_](https://arxiv.org/abs/1703.01664)) .
Iako su svi ovi pristupi doveli do velikog ubrzanja, oni su nažalost ograničeni na unapred zadati skup stilova na kojima je mreža trenirana te se gubi fleksibilnost prethodnog pristupa.

Metodologija koju ću koristiti prevazilazi oba navedena problema. 
Zasniva se na enkoder-dekoder arhitekturi, gde su enkoder i dekoder duboke neuronske mreže simetrične jedna u odnosu na drugu. Novina u ovoj arhitekturi je prisustvo sloja za Adaptivnu Normalizaciju Instanci (AdaIN) ([Huang _et al_](https://arxiv.org/abs/1703.06868)) koji se nalazi izmedju enkodera i dekodera. Njegov ulaz predstavljaju enkodovane slike sadržaja _x_ i stila _y_ i on poravnava srednju vrednost i standardnu devijaciju sadržaja kako bi bili isti kao i kod stila:

<p align="center">
  <img height="80" width="400" src="https://www.henryailabs.com/ArticlePictures/StyleGAN-3.jpg"/>
</p>

Na ovaj način ovaj sloj vrši transfer stila u feature prostoru i omogućava dekoderu da generiše sliku za proizvoljnu kombinaciju slika sadržaj-stil koje mreža nije videla tokom treniranja.

<p align="center">
  <img height="300" width="650" src="https://www.researchgate.net/publication/333617596/figure/fig1/AS:766279258480641@1559706620845/AdaIN-style-transfer-architecture-4.ppm"/>
</p>

## Skup podataka

- za skup podataka slika sadržaja ću koristiti [MS-COCO dataset](https://cocodataset.org/#download)
- a za skup stilova [Wikiart dataset ](https://www.kaggle.com/c/painter-by-numbers/data?select=train_1.zip)

## Evaluacija
Za evaluaciju prenosa stila se ne koriste kvantitativne metode, tako da ću evaluirati kvalitet generisanih slika i porediti sa slikama drugih rešenja za isti ulazni stil i sadržaj.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by kandicst** [comment]
https://github.com/kandicst/real-time-style-transfer
