### ISSUE TITLE
Igranje snake igrice pomoću gestikulacije ruke

### ISSUE THREAD

**Issue by niki299** [ftn-ai-lab/sc-2020-siit#41]
### **Tim:** 

Stojanović Nikola, SW36/2017
Bodroža Jovan, SW44/2017
Jokić Vukašin, SW42/2017

### **Asistent:**

Dragan Vidaković

### **Definicija problema:**

Cilj projekta jeste prepoznavanje gestikulacije ruke u real-time(u), i na osnovu detektovanih pokreta implementirati kontrole za igricu snake.

### **Skup podataka**

Koristićemo set podataka koji će sadržati 4 pozicije šake (gore,dole,levo, desno) i biće kreiran ručno.

### **Metodologija**

**Prvi korak**:  
U prvom koraku se vrši detekcija šake na ulaznom snimku upotrebom tradicionalnih metoda:
- Izdvajanje pozadine upotrebom thresholdinga
- Pronalaženje kontura/regiona
- Detekcija kontura šake na osnovu karakterističnih osobina

**Drugi korak**
U drugom koraku biće upotrebljena konvolutivna neuronska mreža koja će biti istrenirana nad skupom podataka koji smo sami kreirali.
- Prepoznavanje gestikulacije šake putem CNN-a
- Generisanje komande za snake igru

### **Evaluacija**

Kreirani skup podataka bio bi podeljen u trening, validacioni i testni. Kao metriku za evaluaciju rešenja koristićemo accuracy modela. Evaluacija celokupnog resenja zasniva se korisničkom zadovoljstvu.

**Comment by vdragan1993** [comment]
Projekat nema dovoljnu složenost za najveću ocenu za tim od tri člana.
Da li ćete:

1. Ipak raditi ovaj projekat
2. Korigovati prijavu
3. Prijaviti drugu temu

?

**Comment by niki299** [comment]
Postovani, prosirili smo postojeću prijavu, gde detekciju šake sami implementiramo.

**Comment by vdragan1993** [comment]
Projekat i dalje nema dovoljnu složenost za najveću ocenu za tim od tri člana.

**Comment by niki299** [comment]
Postavili smo novi issue sa drugom temom.
