### ISSUE TITLE
Predefinisani projekat 2

### ISSUE THREAD

**Issue by JovanCorilic** [ftn-ai-lab/sc-2020-siit#42]
Student: Jovan Ćorilić sw48/2017

Asistent: Vidaković Dragan

Metodologija: Koristiće se biblioteke OpenCV i matplotlib preko koje će se učitati slika (slike će sve biti pretprocesirane da budu iste dimenzije) i zatim preko HOG će se izdvojiti osobine slike a zatim preko SVM će se izvršiti klasifikacija

Repozitorijum:  https://github.com/JovanCorilic/Predefinisani-2-Soft-komjuting.git

**Comment by vdragan1993** [comment]
Navedena metodologija ne odgovara prirodi problema predefinisanog zadatka 2. 
Korigujte metodologiju.

**Comment by JovanCorilic** [comment]
Da li može ova metodologija?

**Comment by vdragan1993** [comment]
Metodologija i dalje ne odgovara prirodi problema predefinisanog zadataka 2.

**Comment by JovanCorilic** [comment]
Da li je sada uredu metodologija?
