### ISSUE TITLE
Detekcija lica i određivanje pola i godina sa videa u realnom vremenu

### ISSUE THREAD

**Issue by vukasinjokic** [ftn-ai-lab/sc-2020-siit#49]
### *Tim*
Stojanović Nikola, SW36/2017
Bodroža Jovan, SW44/2017
Jokić Vukašin, SW42/2017

### *Asistent*

Dragan Vidaković

### *Definicija problema*

Cilj projekta jeste prepoznavanje lica u realnom vremenu, kao i određjivanje pola i starosti osoba na snimku.

### *Skup podataka*

Koristićemo podskup IMDB/WIKI baze podataka, koja sadrži slike osoba koje sadrže metapodatke o starosti i polu.
Za prepoznavanje lica koristićemo video snimke prikupljene sa interneta.

### *Metodologija*

- Detekcija lica na snimku ce se obavljati pomoću YOLO v3 algoritma.
- Kreiranje konvolutivne neuronske mreže za određivanje pola osobe na snimku.
- Kreiranje konvolutivne neuronske mreže za određivanje starosti osobe.
- Prikaz rezultata na snimku u realnom vremenu

 *Napomena*

Konvolutivne neuronske mreže za prepoznavanje starosti i pola biće trenirane nad istom, IMDB/WIKI bazom podataka, s tim da ce biti korišćeni različiti metapodaci.

### *Evaluacija*

Kao metriku za evaluaciju neuronskih mreža koristićemo accuracy modela. Evaluacija mreža će biti izvršena tako što ćemo svaki skup podataka podeliti u trening, validacioni i test skup nad kojim ćemo vršiti izračunavanje accuracy metrike. Evaluacija celokupnog rešenja biće vršena empirijski

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by niki299** [comment]
https://github.com/niki299/soft-computing-project
