### ISSUE TITLE
Prepoznavanje žanra muzike i emocije u pesmi

### ISSUE THREAD

**Issue by MilicaPoparic** [ftn-ai-lab/sc-2020-siit#5]
### Tim
* Anđela Trajković SW76/2017
* Teodora Nedić SW41/2017
* Milica Poparic SW21/2017

### Asistent
Milica Škipina

# Definicija problema
Cilj projekta je detekcija žanra i prepoznavanje emocije u pesmi na osnovu zvučnog isečka u trajanju od 30 sekundi. Projekat bi podržavao detekciju 10 žanrova u koje spadaju bluz, klasična muzika, kantri, disko, hip hop, džez, metal, pop, rege i rok. Emocije koje bismo detektovale u projektu: sreća, tuga, bes (pri izradi projekta bismo možda imale veći raspon emocija u zavisnosti od toga kako se neuronska mreža bude ponašala).

# Motivacija problema
Sistem bi našao primenu u personalizovanju muzičkih predloga, na primer kreiranja plejliste na osnovu najslušajnijih žanrova  kao i čestih raspoloženja korisnika. 

# Skup podataka
Podatke bismo preuzele sa [linka](https://www.kaggle.com/andradaolteanu/gtzan-dataset-music-genre-classification), izabrani skup podataka sadrži 30 sekundi audio zapisa za 10 žanrova pri čemu svaki žanr ima 100 pesama. Kako nam je skup podataka podeljen na 10 žanrova po folderima, treba još da labeliramo podatke po emocijama.

# Metodologija
Za analizu skupa podataka koristićemo Python-ov paket LibROSA.
Nakon učitavanja skupa podataka treba izdvojiti osobine zvuka, to bismo uradile korišćenjem MFCCs  tehnika.
Sledeći korak bi bila konstrukcija i treniranje više različitih CNN mreža.
Izlaz iz sistema bila bi predikcija žanra pesme kao i emocije koja preovladava.

# Evaluacija
Podatke bismo podelile u trening, validacioni i test skup u razmeri 80:10:10. Korišćene metrike bile bi accuracy i loss. Na osnovu njih bismo odabrale konkretnu neuronsku mrežu koja je pokazala najbolji rezultat.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by Andjelaaa** [comment]
https://github.com/Andjelaaa/SoftComputing
