### ISSUE TITLE
Detekcija saobracajnih znakova u realnom vremenu koristeci kameru

### ISSUE THREAD

**Issue by NikolaMax** [ftn-ai-lab/sc-2020-siit#52]
**Student:** Nikola Maksimovic SW15/2016

**Asistent:** Dragan Vidakovic

**Definicija problema:** Potrebno je izvrsiti klasifikaciju saobracajnih znakova koji budu u vidokrugu kamere. Ulaz u sistem je frejm kamere, na osnovu kog se generise izlaz koji je informacija o klasi (tipu saobracajnog znaka) kao i tacnost kojom se predict-uje ta klasa na osnovu sadrzaja frejma.

**Motivacija:** Detekcija saobracajnih znakova se koristi prilikom kontrole i upravljanja polu-autonomnih vozila, a jednog dana ce se koristiti, sigurno i u potpuno autonomnim vozilima.

**Skup podataka:** Koristice se postojeci skup podataka [(link](https://drive.google.com/file/d/1AZeKw90Cb6GgamTBO3mvDdz6PjBwqCCt/view)) koji sadrzi 30000+ slika od 40+ klasa. Podaci ce biti izdeljeni na 3 grupe: train, test i validation u odnosu: 64:20:16.

**Metodologija:** Koristice se biblioteke _opencv_, _keras_ i _tensorflow_. Svaka slika iz skupa podataka ce biti predprocesirana (konvertovanje u _grayscale_, standardizacija osvetljenja i normalizacija). Takodje, vrsice se augmentacija, kako bi se izbegao _"overfitting"_ i kako bi se povecala generalizacija modela. _CNN_ model bi se sastojao od nekoliko konvolutivnih slojeva, _max-pooling_ i _Dense_ slojeva, kao i po jedan _Flatten_ i _Dropout_ sloj. 

**Evaluacija:** Metrike koje bi se koristile za evaluaciju _CNN_ bi bile accuracy i loss.

**Comment by vdragan1993** [comment]
Da li će se koristiti postojeći skup podataka, ili će se podaci samostalno skupljati?
Ako će se koristiti postojieći skup podataka, neophodno ga je navesti i ostaviti link za pristup podacima.

**Comment by NikolaMax** [comment]
Specifikacija je izmenjena u skladu sa komentarom. Koristice se postojeci skup podataka, koji ce biti blago izmenjen (pregrupisan) tokom izrade projektnog resenja.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by NikolaMax** [comment]
Link ka repozitorijumu je (https://github.com/NikolaMax/trafficSignDetection). Hvala.
