### ISSUE TITLE
Detekcija i čitanje koda sa slike

### ISSUE THREAD

**Issue by alek98** [ftn-ai-lab/sc-2020-siit#6]
**Tim:** Aleksandar Vujinović sw46/2017

**Asistent:** Vidaković Dragan

**Motivacija**
_Screenshot_-ovi koda se razmenjuju svaki dan. Programer mora ručno da prekuca kod koji je dobio. Softver bi rešio problem ručnog prekucavanja koda, a omogućio bi da se automatski preuzme tekstualna reprezentacija koda sa slike.

**Definicija problema**
Detekcija i čitanje koda i komentara sa slike, odnosno _screenshot_-a u vise redova. Treba prepoznati ASCII karaktere, napraviti dobru identaciju koda.

_Primer 1_
_Ulazna slika:_

![example1](https://user-images.githubusercontent.com/3890502/103219106-15968f80-491d-11eb-9b53-a7afd9267227.png)

_Izlazni tekst:_
```java
    private HttpHeaders withoutTokenHeaders = new HttpHeaders();


    @Before
    public void login() {
        ResponseEntity<AuthUserLoginResponseDTO> responseEntity = restTemplate.postForEntity("/auth/login",
                new AuthUserLoginDTO(ADMIN_EMAIL, ADMIN_PASS), AuthUserLoginResponseDTO.class);

        String accessToken = "Bearer " + responseEntity.getBody().getAccessToken();

        headers = new HttpHeaders();
        headers.add("Authorization", accessToken);

        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.add("Content-Type", "application/json");
    }
```

Kod editor može biti u različitim temama (tamna ili svetla). Kod može biti različtih veličina fonta. Naglasak na jezicima python i java. Omogućiti podršku za različite kod editore (vs code, pycharm i eclipse). Segmentacija slike tako da se ukloni activity,  menu bar, status bar,  da ostane samo central widget. Labelirati slike tako da se model može obučiti.

_Primer 2_
_Ulazna slika:_

![example2](https://user-images.githubusercontent.com/3890502/103218702-12e76a80-491c-11eb-8478-192f08d2c303.png)

_Izlazni tekst:_
```java
    private HttpHeaders withoutTokenHeaders = new HttpHeaders();


    @Before
    public void login() {
        ResponseEntity<AuthUserLoginResponseDTO> responseEntity = restTemplate.postForEntity("/auth/login",
                new AuthUserLoginDTO(ADMIN_EMAIL, ADMIN_PASS), AuthUserLoginResponseDTO.class);

        String accessToken = "Bearer " + responseEntity.getBody().getAccessToken();

        headers = new HttpHeaders();
        headers.add("Authorization", accessToken);

        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.add("Content-Type", "application/json");
    }
```
**Metodologija**
_Tesseract OCR_ za detekciju teksta. _Mask R-CNN_ za detekciju i prepoznavanje koda.

**Skup podataka**
Skup podataka pravim sam, screenshot-ovima različitih kodova, u različitim temama, u različitim editorima. Postoji skup za testiranje i skup za treniranje. Za testiranje postoje slike kodova i njima odgovarajući tekstualni fajlovi koji sadrže kod.

**Evaluacija sistema**
Postoji skup za testiranje pomoću kojeg se evaluira rešenje. Skup se sastoji od slika i tekstualnih fajlova. Evaluacija rezultata se vrši na osnovu _Cosine Similarity_ metrike.

**Git Repo:** https://github.com/alek98/extract-code-from-image

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.
