### ISSUE TITLE
Prepoznavanje slova znakovnog jezika 

### ISSUE THREAD

**Issue by danielamet** [ftn-ai-lab/sc-2020-siit#60]
**Tim**
Daniela Metikoš sw-81/2017

**Asistent**
Dragan Vidaković

**Definicija** **problema** 
Prepoznavanje slova znakovnog jezika upotrebom CNN

**Skup **podataka**** 
[https://www.kaggle.com/datamunge/sign-language-mnist](https://www.kaggle.com/datamunge/sign-language-mnist)

**Metodologija** 
Pretprocesiranje i obrada slika vršiće se konvertovanjem u grayscale i normalizacijom, dok će se za obučavanje modela koristiti CNN. 

**Evaluacija**   
Kao metrika koristiće se mera tačnosti, upoređivanjem prediktovanog i stvarnog slova na testnom skupu slika.

**Comment by vdragan1993** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by danielamet** [comment]
https://github.com/danielamet/sign-language-prediction
