### ISSUE TITLE
Prepoznavanje pesme na osnovu isečka u igri SongPop2

### ISSUE THREAD

**Issue by verak13** [ftn-ai-lab/sc-2020-siit#9]
**Tim**
•	Nikola Papić SW4/2017
•	Dušan Stojančević SW11/2017
•	Vera Kovačević SW19/2017

**Asistenti**
Milica Škipina
Dragan Vidaković

**Definicija problema**
Cilj projekta je automatizovano prepoznavanje pesme u video igri _SongPop2_. Igra pušta isečak pesme 10 sekundi i za to vreme je potrebno odabrati jedan od 4 ponuđena odgovora koji predstavljaju ili numeru ili izvođača. Mi bismo automatizovali taj proces odabira tačnog odgovora.

**Motivacija problema**
Ovaj problem je primer rešavanja problema prepoznavanja pesme na osnovu isečka. Šira primena ovog problema može biti prepoznavanje nepoznatih pesama. Takođe, može poslužiti za detekciju plagijata i kršenja autorskih prava u okviru sadržaja na internetu koji sadrži muziku.

**Skup podataka**
Koristili bismo jednu od plejlista dostunih u igri, koja sadrži 50-100 pesama. Isečke bismo generisali ručno. Za prepoznavanje ponuđenih odgovora koristili bismo slike ekrana aplikacije.

**Metodologija**
Za prepoznavanje pesme koristili bismo _“An Industrial-Strength Audio Search Algorithm”_, koji je osnova za aplikaciju Shazam. Algoritam na osnovu spektrograma hešira pesmu i čuva je u bazi, koju kasnije pretražuje na osnovu isečka pesme koju pokušava da prepozna. Pored toga, po potrebi bismo istražili i druge metodologije.
Za prepoznavanje ponuđenih odgovora koristili bismo implementaciju OCR-a.

**Evaluacija**
Na osnovu reakcije igre (da li odgovor tačan ili ne) evaluiraćemo naše rešenje. Kao metriku bismo koristili accuracy.

**Comment by milica-skipina** [comment]
Tema odobrena.
Ostavite link ka GitHub repozitorijumu projekta.
Srećan rad.

**Comment by verak13** [comment]
https://github.com/verak13/SoftComputing
